#ifndef __APIOFIRM_COLOUR_DEFINITIONS_
#define __APIOFIRM_COLOUR_DEFINITIONS_

#define BLACK 0x00000000
#define WHITE ~BLACK

#define FG_BEE 0x00E8BB4A
#define BG_BEE ~FG_BEE

#define HARDRED 0xFF0000
#define HARDGREEN 0x00FF00
#define HARDBLUE 0x0000FF

#define HARDCYAN ~HARDRED
#define HARDMAGENTA ~HARDGREEN
#define HARDYELLOW ~HARDBLUE

#define SOFTRED 0xEB4034
#define SOFTGREEN 0x32A852
#define SOFTBLUE 0x3D6DF2

#define SOFTCYAN ~SOFTRED
#define SOFTMAGENTA ~SOFTGREEN
#define SOFTYELLOW ~SOFTBLUE

#endif
